name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: microsoft

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew build

      - name: Get commit hash
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Rename jar
        run: |
          mkdir release
          cp build/libs/autoaim-1.20.1-*.jar release/AutoAim-${{ steps.vars.outputs.sha_short }}.jar

      - name: Create / Update Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Latest Build (${{ steps.vars.outputs.sha_short }})
          files: release/*.jar